package com.thaiinsure.rules.claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ClaimDocument implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Description("e.g. prescription or bill")
   private java.lang.String documentType;
   private java.util.Date createDate;
   private java.lang.String garageName;

   private java.lang.Integer repairFee;

   private java.lang.String repairCategory;

   public ClaimDocument()
   {
   }

   public java.lang.String getDocumentType()
   {
      return this.documentType;
   }

   public void setDocumentType(java.lang.String documentType)
   {
      this.documentType = documentType;
   }

   public java.util.Date getCreateDate()
   {
      return this.createDate;
   }

   public void setCreateDate(java.util.Date createDate)
   {
      this.createDate = createDate;
   }

   public java.lang.String getGarageName()
   {
      return this.garageName;
   }

   public void setGarageName(java.lang.String garageName)
   {
      this.garageName = garageName;
   }

   public java.lang.Integer getRepairFee()
   {
      return this.repairFee;
   }

   public void setRepairFee(java.lang.Integer repairFee)
   {
      this.repairFee = repairFee;
   }

   public java.lang.String getRepairCategory()
   {
      return this.repairCategory;
   }

   public void setRepairCategory(java.lang.String repairCategory)
   {
      this.repairCategory = repairCategory;
   }

   public ClaimDocument(java.lang.String documentType, java.util.Date createDate,
         java.lang.String garageName, java.lang.Integer repairFee,
         java.lang.String repairCategory)
   {
      this.documentType = documentType;
      this.createDate = createDate;
      this.garageName = garageName;
      this.repairFee = repairFee;
      this.repairCategory = repairCategory;
   }

}