package com.thaiinsure.rules.claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Coverage implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String coverageId;
   private java.lang.Integer coverageAmount;
   private java.lang.String coverageType;
   private java.lang.String coverageLevel;
   private java.lang.String coverageDescription;
   private java.lang.String coverageTerms;

   public Coverage()
   {
   }

   public java.lang.String getCoverageId()
   {
      return this.coverageId;
   }

   public void setCoverageId(java.lang.String coverageId)
   {
      this.coverageId = coverageId;
   }

   public java.lang.Integer getCoverageAmount()
   {
      return this.coverageAmount;
   }

   public void setCoverageAmount(java.lang.Integer coverageAmount)
   {
      this.coverageAmount = coverageAmount;
   }

   public java.lang.String getCoverageType()
   {
      return this.coverageType;
   }

   public void setCoverageType(java.lang.String coverageType)
   {
      this.coverageType = coverageType;
   }

   public java.lang.String getCoverageLevel()
   {
      return this.coverageLevel;
   }

   public void setCoverageLevel(java.lang.String coverageLevel)
   {
      this.coverageLevel = coverageLevel;
   }

   public java.lang.String getCoverageDescription()
   {
      return this.coverageDescription;
   }

   public void setCoverageDescription(java.lang.String coverageDescription)
   {
      this.coverageDescription = coverageDescription;
   }

   public java.lang.String getCoverageTerms()
   {
      return this.coverageTerms;
   }

   public void setCoverageTerms(java.lang.String coverageTerms)
   {
      this.coverageTerms = coverageTerms;
   }

   public Coverage(java.lang.String coverageId, java.lang.Integer coverageAmount,
         java.lang.String coverageType, java.lang.String coverageLevel,
         java.lang.String coverageDescription, java.lang.String coverageTerms)
   {
      this.coverageId = coverageId;
      this.coverageAmount = coverageAmount;
      this.coverageType = coverageType;
      this.coverageLevel = coverageLevel;
      this.coverageDescription = coverageDescription;
      this.coverageTerms = coverageTerms;
   }

}