package com.thaiinsure.rules.claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InsurancePolicyCoverage implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String agreementId;
   private java.lang.String applicationId;
   private java.lang.String customerId;
   private java.lang.String coverageId;

   public InsurancePolicyCoverage()
   {
   }

   public java.lang.String getAgreementId()
   {
      return this.agreementId;
   }

   public void setAgreementId(java.lang.String agreementId)
   {
      this.agreementId = agreementId;
   }

   public java.lang.String getApplicationId()
   {
      return this.applicationId;
   }

   public void setApplicationId(java.lang.String applicationId)
   {
      this.applicationId = applicationId;
   }

   public java.lang.String getCustomerId()
   {
      return this.customerId;
   }

   public void setCustomerId(java.lang.String customerId)
   {
      this.customerId = customerId;
   }

   public java.lang.String getCoverageId()
   {
      return this.coverageId;
   }

   public void setCoverageId(java.lang.String coverageId)
   {
      this.coverageId = coverageId;
   }

   public InsurancePolicyCoverage(java.lang.String agreementId,
         java.lang.String applicationId, java.lang.String customerId,
         java.lang.String coverageId)
   {
      this.agreementId = agreementId;
      this.applicationId = applicationId;
      this.customerId = customerId;
      this.coverageId = coverageId;
   }

}