package com.thaiinsure.rules.claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Policy implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String policyId;
   private java.lang.String policyName;
   private java.util.Date startDate;
   private java.util.Date endDate;

   public Policy()
   {
   }

   public java.lang.String getPolicyId()
   {
      return this.policyId;
   }

   public void setPolicyId(java.lang.String policyId)
   {
      this.policyId = policyId;
   }

   public java.lang.String getPolicyName()
   {
      return this.policyName;
   }

   public void setPolicyName(java.lang.String policyName)
   {
      this.policyName = policyName;
   }

   public java.util.Date getStartDate()
   {
      return this.startDate;
   }

   public void setStartDate(java.util.Date startDate)
   {
      this.startDate = startDate;
   }

   public java.util.Date getEndDate()
   {
      return this.endDate;
   }

   public void setEndDate(java.util.Date endDate)
   {
      this.endDate = endDate;
   }

   public Policy(java.lang.String policyId, java.lang.String policyName,
         java.util.Date startDate, java.util.Date endDate)
   {
      this.policyId = policyId;
      this.policyName = policyName;
      this.startDate = startDate;
      this.endDate = endDate;
   }

}