package com.thaiinsure.rules.claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Policy implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String agreementId;

   public Policy()
   {
   }

   public java.lang.String getAgreementId()
   {
      return this.agreementId;
   }

   public void setAgreementId(java.lang.String agreementId)
   {
      this.agreementId = agreementId;
   }

   public Policy(java.lang.String agreementId)
   {
      this.agreementId = agreementId;
   }

}