package com.thaiinsure.rules.claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProcessType implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Description(value = "e.g. automated , manual")
   private java.lang.String processType;
   private java.lang.String processTypeReason;

   public ProcessType()
   {
   }

   public java.lang.String getProcessType()
   {
      return this.processType;
   }

   public void setProcessType(java.lang.String processType)
   {
      this.processType = processType;
   }

   public java.lang.String getProcessTypeReason()
   {
      return this.processTypeReason;
   }

   public void setProcessTypeReason(java.lang.String processTypeReason)
   {
      this.processTypeReason = processTypeReason;
   }

   public ProcessType(java.lang.String processType,
         java.lang.String processTypeReason)
   {
      this.processType = processType;
      this.processTypeReason = processTypeReason;
   }

}